### ISSUE TITLE
Screenshot export result has different color tones

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#73]
In some examples the differences are more noticeable than others. @edwin is this due to a late color space correction?

The examples below were created with 32 bit color buffers within the compositor.

Examples:

Left: Screenshot - Right: Openrndr Window
<img width="1239" alt="Screenshot 2020-03-04 at 11 57 20" src="https://user-images.githubusercontent.com/8850708/75873397-1e5b2980-5e10-11ea-805f-65bfea3fa242.png">

Left: Openrndr Window - Right: Screenshot
<img width="1316" alt="Screenshot 2020-03-04 at 10 00 11" src="https://user-images.githubusercontent.com/8850708/75873405-21eeb080-5e10-11ea-9501-2effd3f47a84.png">

Left: Openrndr Window - Right: Screenshot
<img width="1357" alt="Screenshot 2020-03-04 at 09 55 56" src="https://user-images.githubusercontent.com/8850708/75873411-231fdd80-5e10-11ea-9687-99737f2f2742.png">

Here is the Screenshots usage:

```kotlin
            extend(Screenshots()) {
                scale = 4.0
                multisample = BufferMultisample.SampleCount(12)
            }
````

**Comment by ricardomatias** [comment]
As far as I understand this is happening due to the algorithm not being able to produce the same result for different resolutions. I assume that there are no actual code changes that can mitigate this.

@edwinRNDR any tips besides extensive use of width/height tied variables?

**Comment by edwinRNDR** [comment]
Interesting. This is a problem that exists with the filters in general. I think this should be addressed by normalizing the parameters _somehow_, which is likely a best-effort kind of deal for some filters.

In the case of the PoissonFill filter I would expect it to create comparable results, but this turns out to be not entirely the case. I need some time to give you a better answer.
